export const ADD_RESERVATION_REQUEST = 'ADD_RESERVATION_REQUEST';
export const DELETE_RESERVATION_REQUEST = 'DELETE_RESERVATION_REQUEST';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';
export const UPDATE_RESERVATION = 'UPDATE_RESERVATION';
export const ADD_RESERVATION = 'ADD_RESERVATION';
